language: node_js
node_js:
  - 12

before_script:
  - cp .env.test.example .env.test
  - yarn install
  - yarn add codecov -D

script:
  - yarn test:ci
  - codecov --file ./tests/coverage/lcov.info --disable search